live: False  
symbol: BTCUSDT
leverage: 1
initial_balance: 5000
use_full_balance: true
qty: null

intervals:
  small: 1m
  medium: 15m
  big: 1h
limits:
  small: 1500
  medium: 500
  big: 100
backtest_period_days: 365

# Strategy parameters
params:
  sl_mult: 2.4
  tp_mult: 3.6
  rsi_extreme_long: 80
  rsi_extreme_short: 20
  rsi_long_open_threshold: 45
  rsi_long_qty_threshold: 30
  rsi_long_close_threshold: 65
  rsi_short_open_threshold: 55
  rsi_short_qty_threshold: 70
  rsi_short_close_threshold: 35
  trail_atr_mult: 0.3
