live: False  
symbol: BTCUSDT
leverage: 1
initial_balance: 5000
use_full_balance: true
qty: null

intervals:
  small: 15m
  medium: 1h
  big: 4h
limits:
  small: 1500
  medium: 500
  big: 100
backtest_period_days: 365

# Strategy parameters
params:
  sl_mult: 3.1
  tp_mult: 1.4
  rsi_extreme_long: 90
  rsi_extreme_short: 10
  rsi_long_open_threshold: 75
  rsi_long_qty_threshold: 35
  rsi_long_close_threshold: 70
  rsi_short_open_threshold: 25
  rsi_short_qty_threshold: 65
  rsi_short_close_threshold: 30
  trail_atr_mult: 0.055
