live: true
symbol: BTCUSDT
leverage: 3
use_full_balance: true
qty: null
intervals:
  small: 1m
  medium: 1h
  big: 4h
indicator_inputs:
  ema: intrabar
  rsi: closed
  bb: closed
  atr: intrabar
params:
  sl_mult: 3.8
  tp_mult: 1.8
  rsi_extreme_long: 91
  rsi_extreme_short: 7
  rsi_long_open_threshold: 80
  rsi_long_qty_threshold: 32
  rsi_long_tp_threshold: 57
  rsi_long_close_threshold: 70
  rsi_short_open_threshold: 20
  rsi_short_qty_threshold: 68
  rsi_short_tp_threshold: 41
  rsi_short_close_threshold: 30
  trail_atr_mult: 0.04
